### ISSUE TITLE
Include the count in the PCR and the fuse logs.

### ISSUE THREAD

**Issue by ajisaxena** [chipsalliance/caliptra-sw#329] opened 2023-05-30 17:30 UTC
Both the PCR and FUSE logs were basically designed to be no more than the snap-shot of the values. The entry-id of the log decides the location where the entry goes. This was done for the ease of parsing. 

It has been requested that both the logs should have a count in them. This issue is created to keep track of that discussion and make a decision on that. 

_Originally posted by @jhand2 in https://github.com/chipsalliance/caliptra-sw/pull/310#discussion_r1207082028_

**Comment by mhatrevi** [comment] 2023-06-02 15:27
Duplicate of https://github.com/chipsalliance/caliptra-sw/issues/343

**Closed by mhatrevi** 2023-06-02 15:27 UTC
Labels: ROM
